const menu = [
  {
    id: 1,
    title: 'Dosa',
    category: 'breakfast',
    price: 50,
    img: 'https://res.cloudinary.com/drrqslttj/image/upload/v1636613876/wp6734909_cvsarp.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Briyani',
    category: 'lunch',
    price: 200,
    img: 'https://res.cloudinary.com/drrqslttj/image/upload/v1636614124/fish-biryani-with-basmati-rice-indian-food-picture-id488481490_jclp2z.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 120,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'idli',
    category: 'breakfast',
    price: 30,
    img: 'https://res.cloudinary.com/drrqslttj/image/upload/v1636614060/idly-sambar-or-idli-with-sambhar-and-green-red-chutney-popular-south-picture-id1024549286_uzkgom.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Paneer Tikka',
    category: 'lunch',
    price: 250,
    img: 'https://res.cloudinary.com/drrqslttj/image/upload/v1636614384/paneer-tikka_xqzc54.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 150,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Sandwhich',
    category: 'breakfast',
    price: 50,
    img: 'https://res.cloudinary.com/drrqslttj/image/upload/v1636613948/1727379_ffkyia.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 100,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Butter Chicken',
    category: 'lunch',
    price: 300,
    img: 'https://res.cloudinary.com/drrqslttj/image/upload/v1636614244/Butter-chicken-bidnia_ijaext.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
